matrix:
  include:
  - language: bash
    name: Compatibility Test (Default OS)
    os: linux
    arch: arm64-graviton2
    script:
    - "./demos/os-detect-full-example.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: dy1Y+5q3m0QZXlTxXFYkMwIFtD7RnD2cEdUEvvxjxSDvafSfdiV9xsRqoWfYwkY6ASU7h1AexeRkTyR39DCJTdvcT2xqIDeYciz9La8EOfwTHTSBKHNzRetkVif/4/pmwu/eQuVFidQ5cp8MhuYJhV8B3O9z1l3tOmqQBneO5k4y8QuMEdoT+ujLU5K/cA61Ely4mvPFA09nlU+0Pao+6aSwY8wO0IgHIIgFg2ui6MdUd5WAOkVDqxqm+S5ewLrRH9rOC3fVkQtq0s4P0GzE69M6cUBeWv2AloThQTNi/3DebsGuINqv+nTKd9ZQeUdajUmub//kmnXLw+zaPd47ZA15QOu94phZNwPBJ99PxTUV68wnGzk12gBZ4tS1imMVfkQlqG9yYciN+vIYyweCxBTyND/XlvxRoBi0JVPTtpUjB26/m5YUIfsVY3UlTKVJiwB7vjBm2a2mIb6EW8+8qRfonsIrqiD+GR7qIh1mT77/Kampt1OqHtZe9ylB/7kDLm14H/STHJeDcUIvZZ+4dJPRbsuRc/x0mR05GqaEePeuqD9XwBMt78m/Tjntc3ugV2H1Fi7YZtzmShp1JfyqXkd9seJm2x+BGPkHuByXunWmwQlr4DjTPewzJYa5u458a1xxHacDa6PkPEgKd0ey6fesn5bmCmZj0uMgBoJVUXg=
