matrix:
  include:
  - language: bash
    name: Compatibility Test (Default OS)
    os: linux
    arch: arm64-graviton2
    script:
    - "./demos/os-detect-full-example.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: kRpDSyr4723LjN9WRu/JaH9Bk1dqi1UgA7afJ5aV9gXJm5NcjBLN/Vl7tHc6oWfwKiATq9rPPgeZTX4B+MC8AjTL2oumRzOI3vJKNGgjXahmRkH38sx1B/fp/nHepO7d9ntkSHXh2tVpoXcnN6KsRTDjrxI+Wg9VQtRhVBSGEKifd+pRo/QhMJWK7BT8S5PdMb4SKucsmmZJS8Yg0oxOl96lDAIpj2JcQKXLCGiOgt7aHCV40jB82OKTGRh5bFugq7utsLZWuHeeHqXgUXhQ6hP+TPwfdrzWU587CdRR3Kt3+i6NF2NcVN/u1KVzsxqTYzx+zNp0r3xKnOOiXPF4IuPa5MeiEoBvF0VBZ/VRSJceH6u5vdNLAduNXFtBB3nVS6Nz73VBJxp5+N2zEdsPyaVDuRyMSHPHrJcYGrIsBoDYXRKfd/YhFGQt8tTID6sFRefuHaPt8mIJ22PuTnM5Oc8tqEgPxNDo+miHF1dso7CFqVUol81jAeH0Wve72easuuZeo2SNlxWQRt/Jn4lCJeOk9ZK5ztcERQl2GXTUXlu3KcVBYexV/KWoI76PO2d0nK8QqvLn7eTrDryslY5R5/nQteIaqTB5RmFkvLIRLiawM8QEDrhLQmUpl3i0rxZw1aLNJHHf4/lv01h1trtm/PL9jxaeVviDM+2rY6D6XWU=
